### ISSUE TITLE
The expression 'pcap_packet_header.incl_len' needs to be clear

### ISSUE THREAD

**Issue by yaohuixguo** [DMTF/spdm-dump#60]
Passing  expression `pcap_packet_header.incl_len` to `fread`, which uses it as an offset.
`pcap_packet_header.incl_len` is an uncertain value, which may cause `m_pcap_packet_data_buffer` to be affected line 141.
https://github.com/DMTF/spdm-dump/blob/1485e03a1d1f0f3ad83012afd7e0a2cde566c2fc/spdm_dump/spdm_dump_pcap.c#L136-L142

same issues:
`m_pcap_global_header.snap_len` needs to judge the range.
https://github.com/DMTF/spdm-dump/blob/1485e03a1d1f0f3ad83012afd7e0a2cde566c2fc/spdm_dump/spdm_dump_pcap.c#L85-L90

**Comment by Xiaohanjlll** [comment]
I will check it.
